"""PrivateDnsZone component module."""

from __future__ import annotations

import dataclasses
from typing import Any

import pulumi
import pulumi_azure_native.privatedns as azure_privatedns


@dataclasses.dataclass
class VnetLinkArgs:
    """Arguments for a single VNet link attached to a Private DNS Zone.

    Attributes:
        vnet_id:              Fully-qualified resource ID of the virtual network
                              to link (e.g. the ``id`` output of a
                              :class:`~pulumi_azure_modules.networking.VirtualNetwork`).
        registration_enabled: Enable auto-registration of VM DNS records in
                              this zone.  Defaults to ``False``.
        link_name:            Explicit Azure resource name for the VNet link.
                              The provider auto-generates a name when ``None``.
    """

    vnet_id: pulumi.Input[str]
    registration_enabled: pulumi.Input[bool] = False
    link_name: pulumi.Input[str] | None = None


class PrivateDnsZone(pulumi.ComponentResource):
    """Creates an Azure Private DNS Zone with optional VNet links.

    Example::

        from pulumi_azure_modules.networking import (
            PrivateDnsZone,
            VnetLinkArgs,
        )

        zone = PrivateDnsZone(
            "blob-dns",
            resource_group_name="rg-platform",
            zone_name="privatelink.blob.core.windows.net",
            vnet_links=[
                VnetLinkArgs(vnet_id=spoke_vnet.id),
                VnetLinkArgs(
                    vnet_id=hub_vnet.id,
                    registration_enabled=True,
                    link_name="hub-link",
                ),
            ],
            tags={"environment": "prod"},
        )

        # Blob storage private endpoint can reference the zone by name:
        # zone_name=zone.name
    """

    name: pulumi.Output[str]
    """The name of the private DNS zone (e.g. ``"privatelink.blob.core.windows.net"``)."""

    id: pulumi.Output[str]
    """The fully-qualified Azure resource ID of the DNS zone.

    Format:
    ``/subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Network/privateDnsZones/{name}``
    """

    resource_group_name: pulumi.Output[str]
    """The resource group the private DNS zone was deployed into."""

    link_ids: pulumi.Output[list[Any]]
    """Resource IDs of all VNet links created for this zone.

    Preserves the same order as ``vnet_links``.  Empty list when no
    ``vnet_links`` were supplied.  Useful for expressing ``depends_on``
    relationships in downstream resources that require the links to exist
    before they can resolve DNS.
    """

    def __init__(
        self,
        resource_name: str,
        resource_group_name: pulumi.Input[str],
        zone_name: pulumi.Input[str] | None = None,
        vnet_links: list[VnetLinkArgs] | None = None,
        tags: pulumi.Input[dict[str, str]] | None = None,
        opts: pulumi.ResourceOptions | None = None,
    ) -> None:
        """Create a Private DNS Zone, then link it to zero or more VNets.

        Args:
            resource_name:       Pulumi logical name (used as the state key).
            resource_group_name: Resource group to deploy the zone into.
            zone_name:           DNS zone name, e.g.
                                 ``"privatelink.blob.core.windows.net"``.
                                 Auto-generated by the provider when ``None``.
            vnet_links:          Zero or more :class:`VnetLinkArgs` entries.
                                 Each entry creates one ``VirtualNetworkLink``
                                 child resource parented to the zone.
            tags:                Azure resource tags applied to the zone (links
                                 do not inherit tags automatically).
            opts:                Pulumi resource options.
        """
        super().__init__(
            "pulumi-azure-modules:networking:PrivateDnsZone",
            resource_name,
            {},
            opts,
        )

        zone = azure_privatedns.PrivateZone(
            resource_name,
            resource_group_name=resource_group_name,
            location="Global",
            private_zone_name=zone_name,
            tags=tags,
            opts=pulumi.ResourceOptions(parent=self),
        )

        created_links: list[azure_privatedns.VirtualNetworkLink] = []
        for i, link in enumerate(vnet_links or []):
            vnet_link = azure_privatedns.VirtualNetworkLink(
                f"{resource_name}-link-{i}",
                resource_group_name=resource_group_name,
                private_zone_name=zone.name,
                location="Global",
                virtual_network=azure_privatedns.SubResourceArgs(id=link.vnet_id),
                registration_enabled=link.registration_enabled,
                virtual_network_link_name=link.link_name,
                opts=pulumi.ResourceOptions(parent=zone),
            )
            created_links.append(vnet_link)

        self.name = zone.name
        self.id = zone.id
        self.resource_group_name = pulumi.Output.from_input(resource_group_name)

        no_links: list[Any] = []
        self.link_ids = (
            pulumi.Output.all(*[lnk.id for lnk in created_links])
            if created_links
            else pulumi.Output.from_input(no_links)
        )

        self.register_outputs(
            {
                "name": self.name,
                "id": self.id,
                "resource_group_name": self.resource_group_name,
                "link_ids": self.link_ids,
            }
        )
