"""RouteTable component module."""

from __future__ import annotations

import dataclasses
from typing import Any

import pulumi
import pulumi_azure_native.network as azure_network


@dataclasses.dataclass
class RouteArgs:
    """Arguments for a single route within a route table.

    Attributes:
        name:                Azure resource name for the route (used as
                             ``route_name``).  Must be unique within the route
                             table.
        next_hop_type:       The type of Azure hop the packet should be sent to.
                             One of ``"VirtualNetworkGateway"``,
                             ``"VnetLocal"``, ``"Internet"``,
                             ``"VirtualAppliance"``, or ``"None"``.
        address_prefix:      The destination CIDR to which the route applies,
                             e.g. ``"10.1.0.0/16"`` or ``"0.0.0.0/0"``.
        next_hop_ip_address: The IP address packets should be forwarded to.
                             Required (and only permitted) when
                             ``next_hop_type`` is ``"VirtualAppliance"``.
    """

    name: pulumi.Input[str]
    next_hop_type: pulumi.Input[str]
    address_prefix: pulumi.Input[str] | None = None
    next_hop_ip_address: pulumi.Input[str] | None = None


class RouteTable(pulumi.ComponentResource):
    """Creates an Azure Route Table with optional routes.

    Each entry in ``routes`` is deployed as a standalone
    ``azure_network.Route`` child resource (not as an inline route on the
    RouteTable resource itself).  This avoids the provider conflict that arises
    when both inline and standalone routes are mixed on the same route table.

    Example::

        from pulumi_azure_modules.networking import RouteTable, RouteArgs

        rt = RouteTable(
            "spoke-rt",
            resource_group_name="rg-platform",
            location="eastus",
            routes=[
                RouteArgs(
                    name="to-internet",
                    next_hop_type="Internet",
                    address_prefix="0.0.0.0/0",
                ),
                RouteArgs(
                    name="to-nva",
                    next_hop_type="VirtualAppliance",
                    address_prefix="10.0.0.0/8",
                    next_hop_ip_address="10.1.0.4",
                ),
            ],
            disable_bgp_route_propagation=True,
            tags={"environment": "prod"},
        )

        # Associate the route table with a subnet by its resource ID:
        # route_table=azure_network.SubResourceArgs(id=rt.id)
    """

    id: pulumi.Output[str]
    """The fully-qualified Azure resource ID of the route table.

    Format:
    ``/subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Network/routeTables/{name}``
    """

    name: pulumi.Output[str]
    """The Azure resource name of the route table."""

    resource_group_name: pulumi.Output[str]
    """The resource group the route table was deployed into."""

    route_ids: pulumi.Output[list[Any]]
    """Resource IDs of all standalone routes created for this route table.

    Preserves the same order as ``routes``.  Empty list when no ``routes``
    were supplied.  Useful for expressing ``depends_on`` relationships in
    downstream resources that require routes to exist before traffic is
    forwarded.
    """

    def __init__(
        self,
        resource_name: str,
        resource_group_name: pulumi.Input[str],
        location: pulumi.Input[str],
        route_table_name: pulumi.Input[str] | None = None,
        routes: list[RouteArgs] | None = None,
        disable_bgp_route_propagation: pulumi.Input[bool] | None = None,
        tags: pulumi.Input[dict[str, str]] | None = None,
        opts: pulumi.ResourceOptions | None = None,
    ) -> None:
        """Create a route table and its routes.

        Args:
            resource_name:                  Pulumi logical name (used as the
                                            state key and name prefix for child
                                            resources).
            resource_group_name:            Resource group to deploy the route
                                            table into.
            location:                       Azure region (e.g. ``"eastus"``).
            route_table_name:               Explicit Azure resource name for the
                                            route table.  Auto-generated by the
                                            provider when ``None``.
            routes:                         Zero or more :class:`RouteArgs`
                                            entries.  Each entry creates one
                                            standalone ``Route`` child resource.
            disable_bgp_route_propagation:  When ``True``, BGP-learned routes
                                            are not propagated to the route
                                            table.  Defaults to provider default
                                            (``False``) when ``None``.
            tags:                           Azure resource tags applied to the
                                            route table.
            opts:                           Pulumi resource options.
        """
        super().__init__(
            "pulumi-azure-modules:networking:RouteTable",
            resource_name,
            {},
            opts,
        )

        rt = azure_network.RouteTable(
            f"{resource_name}-rt",
            resource_group_name=resource_group_name,
            location=location,
            route_table_name=route_table_name,
            disable_bgp_route_propagation=disable_bgp_route_propagation,
            tags=tags,
            opts=pulumi.ResourceOptions(parent=self),
        )

        created_routes: list[azure_network.Route] = []
        for i, route in enumerate(routes or []):
            r = azure_network.Route(
                f"{resource_name}-route-{i}",
                resource_group_name=resource_group_name,
                route_table_name=rt.name,
                route_name=route.name,
                next_hop_type=route.next_hop_type,
                address_prefix=route.address_prefix,
                next_hop_ip_address=route.next_hop_ip_address,
                opts=pulumi.ResourceOptions(parent=self),
            )
            created_routes.append(r)

        self.id = rt.id
        self.name = rt.name
        self.resource_group_name = pulumi.Output.from_input(resource_group_name)
        if created_routes:
            self.route_ids = pulumi.Output.all(*[r.id for r in created_routes])
        else:
            self.route_ids = pulumi.Output.from_input([])

        self.register_outputs(
            {
                "id": self.id,
                "name": self.name,
                "resource_group_name": self.resource_group_name,
                "route_ids": self.route_ids,
            }
        )
